### ISSUE TITLE
Error get spammed in console

### ISSUE THREAD

**Issue by ghost** [NoahBPeterson/BlockTrack#2] opened 2020-06-22 16:42 UTC
I get this error spammed in my console: https://pastebin.com/3JuUqMff

**Comment by NoahBPeterson** [comment] 2020-06-22 16:57
Try using 1.0.2. I'll try to find a better fix for the database upgrade.

**Comment by ghost** [comment] 2020-06-23 08:17
OK, do I have to delete my old DB?

**Comment by NoahBPeterson** [comment] 2020-06-23 12:42
Not if you just go back to 1.0.2. This removes the code that upgrades the DB. Unfortunately I couldn't find a good place for the upgrade code.

**Comment by ghost** [comment] 2020-06-23 17:04
Ok, thanks, I'll close this and try it out tomorrow.

**Comment by ghost** [comment] 2020-06-26 16:17
Now, with 1.0.2, I get this error: https://pastebin.com/T80zc3VJ

**Comment by NoahBPeterson** [comment] 2020-06-26 16:27
Weird. I'm nbpe#9323 on discord, would you mind sharing your db file with me there?

**Comment by NoahBPeterson** [comment] 2020-06-26 16:42
Or at least try using the DB file on a new server and tell me if breaking a block produces any errors.

**Comment by NoahBPeterson** [comment] 2020-06-26 16:57
It looks like an issue with database synchronization. Unfortunately this is not something I will be able to reproduce on my own as I do not have access to a server with enough players that blocks will be broken in the same tick. Since I believe the issue can be resolved by requiring synchronization, I will add this and let you test it before I make a release.

**Comment by NoahBPeterson** [comment] 2020-06-26 19:06
I regret that I am unable to test this plugin at all due to Nukkit not being updated to 1.16, however I can give it to you for feedback. Let me know how it works: [http://uppit.com/d4osvizpig5v
](url)

**Comment by ghost** [comment] 2020-07-06 11:56
Sorry for reading too late, the link isn't working anymore. Could you send me another?

**Comment by NoahBPeterson** [comment] 2020-07-06 15:09
http://uppit.com/ayzrv1s9wb10

It seems to work on my end, but I have no idea if this would work for you if you have enough players to cause issues with the database being locked.

If this doesn't work, I would suggest not using SQLite and instead using a more traditional database such as a MySQL server. The configuration would be with the DbLib config.yml, but you'd have to set up and run the database server separately.

**Comment by ghost** [comment] 2020-07-31 12:01
Sorry again for the last response. It's now working correctly with 1.0.4. Thanks for this great plugin!

**Comment by ghost** [comment] 2020-08-08 08:49
@NoahBPeterson you can close this, if you want.

**Closed as completed** 2020-08-10 08:50 UTC
